# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pinture' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pinture
  pod 'Firebase/Core'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'LineSDK', '~> 4.0.2'

end

